ICSP.WebProxy/Controllers/InstallController.cs
using System;
using System.IO;

using ICSP.Core.Environment;
using ICSP.Core.Logging;
using ICSP.WebProxy.Configuration;
using ICSP.WebProxy.Extensions;
using ICSP.WebProxy.Models;
using ICSP.WebProxy.Properties;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ICSP.WebProxy.Controllers
{
  public class InstallController : Controller
  {
    // GET: /Install/
    public IActionResult Index()
    {
      return View(new DeviceConfiguration());
    }

    // Post: /Install/
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Index([Bind("PanelType,PortCount,DeviceName")] DeviceConfiguration configuration)
    {
      if(ModelState.IsValid)
      {
        return RedirectToActionPreserveMethod(nameof(Configure));
      }

      return View(configuration);
    }

    // Post: /Install/Configure/ 
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Configure([Bind("PanelType,PortCount,DeviceName")] DeviceConfiguration configuration, [FromServices] IOptions<ProxyConfig> config)
    {
      if(ModelState.IsValid)
      {
        try
        {
          var lConnectionConfig = config.Value.GetConfig(HttpContext);

          // Create js\project.js
          var lProject = Resources.DefaultProject;
          var lBaseDirectory = new DirectoryInfo(lConnectionConfig?.BaseDirectory ?? string.Empty);

          lProject = lProject?
            .Replace("{PanelType}", configuration.PanelType)
            .Replace("{PortCount}", configuration.PortCount.ToString())
            .Replace("{DeviceName}", configuration.DeviceName);

          var lFileNameProject = string.Format(@"{0}\js\{1}", lBaseDirectory.FullName, "project.js");

          System.IO.File.WriteAllText(lFileNameProject, lProject);

          // Create index.html
          var lHtml = Resources.MainPage_V02;

          lHtml = lHtml?
            .Replace("[Title]", string.IsNullOrWhiteSpace(configuration.DeviceName) ? "WebControl" : configuration.DeviceName)
            .Replace("[Width]", "1280")
            .Replace("[Height]", "800");

          // LastBuild & Version
          lHtml = lHtml?
            .Replace("[LastBuild]", ProgramProperties.CompileDate.ToString("yyyy-MM-dd HH:mm:ss:ffffff")) // 2020-08-27 12:03:37.946386
            .Replace("[Version]", ProgramProperties.Version.ToString());

          var lFileNameMainPage = string.Format(@"{0}\{1}", lBaseDirectory.FullName, "index.html");

          System.IO.File.WriteAllText(lFileNameMainPage, lHtml);

          // Redirect to BaseUrl
          return Redirect(this.GetBaseUrl());
        }
        catch(Exception ex)
        {
          Logger.LogError(ex);
        }

        return View(configuration);
      }

      return View(nameof(Index));
    }
  }
}

ICSP.WebProxy/Controllers/ServicesController.cs
using System;

using ICSP.Core.Logging;

using Microsoft.AspNetCore.Mvc;

namespace ICSP.WebProxy.Controllers
{
  public class ServicesController : Controller
  {
    private IApplicationRestart mApplicationLifetime;

    public ServicesController(IApplicationRestart appLifetime)
    {
      mApplicationLifetime = appLifetime;
    }

    // Get: /Services/Restart
    public IActionResult Restart()
    {
      try
      {
        Logger.LogInfo("Restarting App");

        mApplicationLifetime.RestartApplication();
      }
      catch(Exception ex)
      {
        Logger.LogError(ex.Message);
      }
      
      return Redirect("/Services/Wait");
    }

    // Get: /Services/Shutdown
    public IActionResult Shutdown()
    {
      try
      {
        Logger.LogInfo("Shutdown App");

        mApplicationLifetime.StopApplication();
      }
      catch(Exception ex)
      {
        Logger.LogError(ex.Message);
      }

      return View();
    }

    // Get: /Services/Wait
    public IActionResult Wait()
    {
      return View();
    }

    // Get: /Services/Success
    public IActionResult Success()
    {
      return View();
    }
  }
}

ICSP.WebProxy/Controllers/SetupController.cs
using System;
using System.Linq;
using System.Threading.Tasks;

using ICSP.Core.Logging;
using ICSP.WebProxy.Configuration;
using ICSP.WebProxy.Configuration.Options;

using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ICSP.WebProxy.Controllers
{
  public class SetupController : Controller
  {
    // GET: Setup
    public ActionResult Index([FromServices] IOptionsSnapshot<ProxyConfig> config)
    {
      return View(config.Value);
    }

    // GET: Setup/Details/5
    public ActionResult Details(int id, [FromServices] IOptionsSnapshot<ProxyConfig> config)
    {
      var lConfig = config.Value.Connections.Values.FirstOrDefault(p => p.ID == id);

      return View(lConfig);
    }

    // GET: Setup/Create
    public ActionResult Create()
    {
      return View(new ProxyConnectionConfig());
    }

    // POST: Setup/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> CreateAsync(ProxyConnectionConfig model, [FromServices] IWritableOptions<ProxyConfig> config)
    {
      try
      {
        if(ModelState.IsValid)
        {
          await config.UpdateAsync(1000, config =>
          {
            var lID = config?.Connections?.Keys.Select(ushort.Parse).DefaultIfEmpty().Max() + 1 ?? 1;

            config.Connections[lID.ToString()] = model;
          });

          return RedirectToAction(nameof(Index));
        }
      }
      catch(Exception ex)
      {
        Logger.LogError(ex.Message);
      }

      return View();
    }

    // GET: Setup/Edit/5
    public ActionResult Edit(int id, [FromServices] IOptionsSnapshot<ProxyConfig> config)
    {
      var lConfig = config.Value.Connections.Values.FirstOrDefault(p => p.ID == id);

      return View(lConfig);
    }

    // POST: Setup/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> EditAsync(ProxyConnectionConfig model, [FromServices] IWritableOptions<ProxyConfig> config, [FromServices] IDataProtectionProvider provider)
    {
      try
      {
        if(ModelState.IsValid)
        {
          if(!string.IsNullOrEmpty(model.NewPassword))
          {
            var lService = new CipherService(provider);

            model.Password = lService.Encrypt(model.NewPassword);
            model.NewPassword = null;
          }

          await config.UpdateAsync(1000, config => { config.Connections[model.ID.ToString()] = model; });

          return RedirectToAction(nameof(Index));
        }
      }
      catch(Exception ex)
      {
        Logger.LogError(ex.Message);
      }

      return View();
    }

    // GET: Setup/Delete/5
    public ActionResult Delete(int id, [FromServices] IOptionsSnapshot<ProxyConfig> config)
    {
      var lConfig = config.Value.Connections.Values.FirstOrDefault(p => p.ID == id);

      return View(lConfig);
    }

    // POST: Setup/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> DeleteAsync(int id, [FromServices] IWritableOptions<ProxyConfig> config)
    {
      try
      {
        if(ModelState.IsValid)
        {
          await config.UpdateAsync(1000, config =>
          {
            if(config.Connections.ContainsKey(id.ToString()))
              config.Connections.Remove(id.ToString());
          });

          return RedirectToAction(nameof(Index));
        }
      }
      catch(Exception ex)
      {
        Logger.LogError(ex.Message);
      }

      return View();
    }
  }
}

ICSP.WebProxy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ICSP.WebProxy - @ViewData["Title"]</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/lib/fontawesome-free-5.14.0-web/css/all.css" />
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">ICSP.WebProxy</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="~/">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" asp-controller="Setup" asp-action="Index">Setup <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" asp-controller="Install" asp-action="Index">Install</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdownServices" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Services</a>
              <div class="dropdown-menu" aria-labelledby="dropdownServices">
                <a class="dropdown-item" asp-controller="Services" asp-action="Restart">Restart</a>
                <a class="dropdown-item" asp-controller="Services" asp-action="Shutdown">Shutdown</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  </header>
  <main role="main" class="container">
    @RenderBody()
  </main>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2020 - ICSP.WebProxy
    </div>
  </footer>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @RenderSection("Scripts", required: false)
</body>
</html>